[package]
name = "corp-finance-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
corp-finance-core = { path = "../../crates/corp-finance-core" }
napi = { version = "2", features = ["serde-json"] }
napi-derive = "2"
serde_json = "1.0"

[build-dependencies]
napi-build = "2"
